<?php

namespace Action\School\user;

use AW\Action;
use AW\User;

class SignIn extends Action
{
    public function get()
    {
//        parent::get(); // TODO: Change the autogenerated stub
    }

    public function post()
    {
//        parent::post(); // TODO: Change the autogenerated stub

        $user_name = filter_input(INPUT_POST, 'username', FILTER_SANITIZE_STRING);
        $password = filter_input(INPUT_POST, 'password', FILTER_SANITIZE_STRING);
        $ip           = \LT\Network\Client::ip();

        if (($message      = User::authenticate($user_name, $password, $ip)) === TRUE) {
            $this->redirect('/');
        } else if ($message === "change-password") {
            $this->redirect("/change-password");
        } else {
            $this->view->assign('error', $message);
        }

    }
}