<?php

namespace Action\School\user;

use AW\Action;

class SignIn extends Action
{
    public function get()
    {
//        parent::get(); // TODO: Change the autogenerated stub
    }

    public function post()
    {
//        parent::post(); // TODO: Change the autogenerated stub
    }
}