<?php
    namespace Action\Www;

    use \LT\DB;

    class index extends \AW\Action {


        public function get()
        {
//            parent::get(); // TODO: Change the autogenerated stub
            var_dump('testomg');
        }
    }