<?php

namespace Action\School\Comp1006\ActiveUserDetails;

class Index extends \AW\Action {


    public function __construct()
    {
        parent::__construct();

        $input = INPUT_GET;

        switch (filter_input(INPUT_SERVER, 'REQUEST_METHOD')) {
            case 'GET':
                $input = INPUT_GET;
                break;
            case 'POST':
                $input = INPUT_POST;
                break;

        }

//        $input = filter_input(INPUT_GET, 'token');
//        var_dump($input);
    }

    public function get()
    {
        $input = filter_input(INPUT_GET, 'token');
        $active_user = \AW\ActiveClient::findOne([
           'token'  =>  $input
        ]);

        $user_name  = $active_user->first_name. ' '.$active_user->last_name;
        $telephone  = $active_user->tel;
        $email      =   $active_user->email;
        $active_type = $active_user->type;
        $active_group = '';
        $country = $active_user->country;
        if ($active_user->active_id == 1) {
            $active_group = 'Self-Motivated Swimming club';
        }
        $this->view->assign('user_name', $user_name);
        $this->view->assign('telephone', $telephone);
        $this->view->assign('email', $email);
        $this->view->assign('active_type', $active_type);
        $this->view->assign('country', $country);
        $this->view->assign('group',$active_group);

        $active_count = \AW\ActiveFitness::find([
            'active_client_id'  =>  $active_user->id
        ]);

        if(count($active_count) == 0) {
            $this->view->assign('total_count', 0);
            $this->view->assign('total_length', 0);
            $this->view->assign('average_hb', 0);
        }


    }

    public function post()
    {
        parent::post(); // TODO: Change the autogenerated stub
    }

}